### ISSUE TITLE
Is this tool still working?

### ISSUE THREAD

**Issue by adrianmihalko** [Eths/Issuu-Downloader#1]
I am trying to download an publication, but I get error:

https://issuu.com/kenzel/docs/the_perfect_bike_book_2017

```
Traceback (most recent call last):
  File "issuu.py", line 38, in <module>
    code = page_loader.retrieve(line.strip()+str(pageNum)+".jpg", str(pageNum)+".jpg")
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 463, in open_file
    return self.open_local_file(url)
  File "/usr/lib/python2.7/urllib.py", line 477, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: '</html>1.jpg'
```

**Comment by Raafas** [comment]
Sorry, the Issuu website has changed the layout.
Thanks for reporting.
